import {type Context} from '@sanity/client'

export const knowledgeBase: Context.KnowledgeBase = {
  activeJobId: null,
  buildStageState: null,
  createdAt: '2026-08-01T00:00:00.000Z',
  description: 'Product docs and troubleshooting guides',
  hasDatasetSource: false,
  hasPendingChanges: false,
  hasWebSource: false,
  id: '00000000-0000-0000-0000-000000000001',
  instructionCount: 2,
  isBuilding: false,
  lastChangedAt: null,
  lastCheckedAt: null,
  openIssueCount: 1,
  organizationId: 'org-abc123',
  pendingChanges: null,
  pipelineOutdated: false,
  publicId: 'kb-abc123',
  rebuildRecommended: null,
  refreshEnabled: true,
  refreshFrequency: 'weekly',
  refreshInFlight: false,
  refreshNextRunAt: null,
  sourceUsage: null,
  state: 'ready',
  title: 'Support docs',
  updatedAt: '2026-08-02T00:00:00.000Z',
}
