linkWorkspacePackages: true

packages:
  - 'packages/@repo/*'
  - 'packages/@sanity/cli'
  - 'packages/@sanity/cli-core'
  - 'packages/@sanity/cli-test'
  - 'packages/@sanity/eslint-config-cli'
  - 'packages/create-sanity'
  - 'fixtures/*'
  - 'tmp/*'

catalog:
  # Linting
  eslint: ^9.39.4
  '@eslint/compat': ^2.0.3
  publint: ^0.3.18

  # Sanity
  sanity: ^5.17.1
  '@sanity/vision': ^5.17.1
  '@sanity/types': ^5.17.1
  '@sanity/schema': ^5.17.1
  '@sanity/client': ^7.17.0
  '@sanity/codegen': ^6.0.1
  '@sanity/telemetry': ^0.8.1

  # Build & Development Tools
  typescript: ^5.9.3
  vite: ^7.3.1
  tsx: ^4.21.0
  '@vitejs/plugin-react': ^5.2.0

  # Testing
  vitest: ^4.1.0
  '@vitest/coverage-istanbul': ^4.1.0
  nock: ^14.0.11

  # CLI Framework
  '@oclif/core': ^4.9.0
  '@oclif/plugin-help': ^6.2.38
  '@oclif/plugin-not-found': ^3.2.75

  # Utilities
  debug: ^4.4.3
  jsdom: ^28.1.0
  zod: ^4.3.6
  'get-tsconfig': ^4.13.6
  'import-meta-resolve': ^4.2.0
  execa: ^9.6.0
  read-package-up: ^12.0.0
  ora: ^9.0.0
  rxjs: ^7.8.2
  tinyglobby: ^0.2.15
  lodash-es: ^4.17.23
  '@types/lodash-es': ^4.17.12
  yaml: ^2.8.2

  # Build Tools
  '@swc/core': ^1.15.18
  '@swc/cli': ^0.8.0
  rimraf: ^6.0.1
  '@sanity/pkg-utils': ^10.4.11
  oxfmt: ^0.41.0

  # Type Definitions
  '@types/node': ^20.19.37
  '@types/debug': ^4.1.12
  '@types/jsdom': ^28.0.0

minimumReleaseAge: 4320
minimumReleaseAgeExclude:
  - '@portabletext/*'
  - '@sanity/*'
  - '@types/*'
  - 'data-uri-to-buffer@7.0.0'
  - 'get-latest-version@6.0.1'
  - 'get-uri@7.0.0'
  - 'groq-js'
  - 'groq'
  - 'react-rx'
  - 'sanity'
  - 'use-effect-event'
  # Renovate security update: tar@7.5.11
  - tar@7.5.11
