packages:
  - 'packages/@repo/*'
  - 'packages/@sanity/cli'
  - 'packages/@sanity/cli-core'
  - 'packages/@sanity/cli-test'
  - 'packages/@sanity/eslint-config-cli'
  - 'packages/create-sanity'
  - 'examples/*'
  - 'tmp/*'

catalog:
  # Linting
  eslint: ^9.39.2
  '@eslint/compat': ^2.0.1
  publint: ^0.3.17

  # Sanity
  sanity: ^5.6.0
  '@sanity/vision': ^5.6.0
  '@sanity/types': ^5.6.0
  '@sanity/schema': ^5.6.0
  '@sanity/client': ^7.14.1

  # Build & Development Tools
  typescript: ^5.9.3
  vite: ^7.3.1
  tsx: ^4.21.0
  '@vitejs/plugin-react': ^5.1.2

  # Testing
  vitest: ^4.0.18
  '@vitest/coverage-istanbul': ^4.0.18
  nock: ^14.0.10

  # CLI Framework
  '@oclif/core': ^4.8.0
  '@oclif/plugin-help': ^6.2.36
  '@oclif/plugin-not-found': ^3.2.73
  '@oclif/test': ^4.1.15

  # Utilities
  debug: ^4.4.3
  jsdom: ^27.4.0
  zod: ^4.3.6
  'get-tsconfig': ^4.13.0
  execa: ^9.6.0
  ora: ^9.0.0

  # Build Tools
  '@swc/core': ^1.15.10
  '@swc/cli': ^0.7.10
  rimraf: ^6.0.1
  '@sanity/pkg-utils': ^10.3.3

  # Type Definitions
  '@types/node': ^20.19.30
  '@types/debug': ^4.1.12
  '@types/jsdom': ^27.0.0

minimumReleaseAge: 4320
minimumReleaseAgeExclude:
  - '@portabletext/*'
  - '@sanity/*'
  - 'groq-js'
  - 'groq'
  - 'react-rx'
  - 'sanity'
  - 'use-effect-event'
