import fs from 'node:fs/promises'
import path from 'node:path'

import {type AppResource} from '@sanity/cli-core'
import {type Plugin} from 'vite'

const VIRTUAL_ID = 'virtual:sanity/resources'
const RESOLVED_ID = '\0' + VIRTUAL_ID

/**
 * Vite plugin that:
 * 1. Generates a `virtual:sanity/resources` module exporting a typed `resources` map
 * 2. Writes `.sanity/resources.d.ts` to augment `@sanity/sdk`'s `RegisteredResources`
 *    interface so that `ResourceName` is narrowed to the configured resource names
 *
 * Both are no-ops when no resources are configured.
 *
 * @internal
 */
export function sanityResources(resources?: Record<string, AppResource>): Plugin {
  let root: string

  return {
    name: 'sanity/plugin-resources',

    config() {
      return {
        optimizeDeps: {
          exclude: [VIRTUAL_ID],
        },
      }
    },

    async configResolved(config) {
      root = config.root
      await writeDtsFile(root, resources)
    },

    resolveId(id) {
      if (id === VIRTUAL_ID) return RESOLVED_ID
    },

    load(id) {
      if (id !== RESOLVED_ID) return
      return generateVirtualModule(resources)
    },
  }
}

async function writeDtsFile(root: string, resources?: Record<string, AppResource>) {
  const sanityDir = path.join(root, '.sanity')
  await fs.mkdir(sanityDir, {recursive: true})
  await fs.writeFile(path.join(sanityDir, 'resources.d.ts'), generateDts(resources))
}

function generateDts(resources?: Record<string, AppResource>): string {
  const header = `// auto-generated by sanity dev — do not edit\n`

  if (!resources || Object.keys(resources).length === 0) {
    return `${header}export {}\n`
  }

  const keys = Object.keys(resources)
    .map((k) => `    ${JSON.stringify(k)}: true`)
    .join('\n')

  return `${header}declare module '@sanity/sdk' {
  interface RegisteredResources {
${keys}
  }
}
export {}
`
}

function generateVirtualModule(resources?: Record<string, AppResource>): string {
  if (!resources || Object.keys(resources).length === 0) {
    return `export const resources = {}\n`
  }

  const entries = Object.entries(resources)
    .map(
      ([name, {dataset, projectId}]) =>
        `  ${JSON.stringify(name)}: {projectId: ${JSON.stringify(projectId)}, dataset: ${JSON.stringify(dataset)}}`,
    )
    .join(',\n')

  const names = Object.keys(resources)
    .map((k) => JSON.stringify(k))
    .join(' | ')

  return `export type ResourceName = ${names}
export const resources = {
${entries}
}
`
}
