import {readFile, rm} from 'node:fs/promises'
import {tmpdir} from 'node:os'
import {join} from 'node:path'

import {testCommand} from '@sanity/cli-test'
import {afterEach, describe, expect, test, vi} from 'vitest'

import {ResourcesCommand} from '../resources.js'

describe('#resources', () => {
  afterEach(() => {
    vi.clearAllMocks()
  })

  test('errors when run outside an app project', async () => {
    const {error} = await testCommand(ResourcesCommand, [], {
      mocks: {
        cliConfig: {api: {dataset: 'production', projectId: 'test-project'}},
        projectRoot: {directory: '/tmp/test', path: '/tmp/test/sanity.cli.ts', type: 'app'},
      },
    })

    expect(error).toBeInstanceOf(Error)
    expect(error?.message).toContain('only available for Sanity app projects')
    expect(error?.oclif?.exit).toBe(1)
  })

  test('prints info and returns early when app has no resources configured', async () => {
    const {error, stdout} = await testCommand(ResourcesCommand, [], {
      mocks: {
        cliConfig: {app: {entry: './src/App.tsx', organizationId: 'org-id'}},
        projectRoot: {directory: '/tmp/test', path: '/tmp/test/sanity.cli.ts', type: 'app'},
      },
    })

    if (error) throw error
    expect(stdout).toContain('No resources configured')
    expect(stdout).toContain('app.resources')
  })

  test('prints info and returns early when resources is an empty object', async () => {
    const {error, stdout} = await testCommand(ResourcesCommand, [], {
      mocks: {
        cliConfig: {app: {entry: './src/App.tsx', organizationId: 'org-id', resources: {}}},
        projectRoot: {directory: '/tmp/test', path: '/tmp/test/sanity.cli.ts', type: 'app'},
      },
    })

    if (error) throw error
    expect(stdout).toContain('No resources configured')
  })

  test('generates .sanity/resources.ts when resources are configured', async () => {
    const tmpDir = join(tmpdir(), `sanity-resources-test-${Date.now()}`)

    try {
      const {error, stdout} = await testCommand(ResourcesCommand, [], {
        mocks: {
          cliConfig: {
            app: {
              entry: './src/App.tsx',
              organizationId: 'org-id',
              resources: {
                default: {dataset: 'production', projectId: 'test-project'},
              },
            },
          },
          projectRoot: {directory: tmpDir, path: join(tmpDir, 'sanity.cli.ts'), type: 'app'},
        },
      })

      if (error) throw error
      expect(stdout).toContain('Generated .sanity/resources.ts')

      const content = await readFile(join(tmpDir, '.sanity', 'resources.ts'), 'utf8')
      expect(content).toContain('"default": {projectId: "test-project", dataset: "production"}')
      expect(content).toContain('RegisteredResources')
      expect(content).toContain('satisfies Record<string, DocumentResource>')
      expect(content).toContain('auto-generated by sanity CLI')
    } finally {
      await rm(tmpDir, {force: true, recursive: true})
    }
  })

  test('generates .sanity/resources.ts with multiple resources', async () => {
    const tmpDir = join(tmpdir(), `sanity-resources-test-${Date.now()}`)

    try {
      const {error} = await testCommand(ResourcesCommand, [], {
        mocks: {
          cliConfig: {
            app: {
              entry: './src/App.tsx',
              organizationId: 'org-id',
              resources: {
                default: {dataset: 'production', projectId: 'proj-a'},
                secondary: {dataset: 'staging', projectId: 'proj-b'},
              },
            },
          },
          projectRoot: {directory: tmpDir, path: join(tmpDir, 'sanity.cli.ts'), type: 'app'},
        },
      })

      if (error) throw error

      const content = await readFile(join(tmpDir, '.sanity', 'resources.ts'), 'utf8')
      expect(content).toContain('"default": {projectId: "proj-a", dataset: "production"}')
      expect(content).toContain('"secondary": {projectId: "proj-b", dataset: "staging"}')
      expect(content).toContain('"default": true')
      expect(content).toContain('"secondary": true')
    } finally {
      await rm(tmpDir, {force: true, recursive: true})
    }
  })
})
